### ISSUE TITLE
unrecognized function or variable 'surfinterior'

### ISSUE THREAD

**Issue by wpgao-hit** [luxneuroimage/FastField#1]
Hi,

FastField is a nice work. However, when i download and run it under Matlab 2019b. I encounter a problem that the function 'surfinterior' was unrecognized. So, is there any file missing? Thanks

**Comment by MehriB** [comment]
Hello,
There was an unnecessary step which has been removed now. There should be no surfinterior needed. Please try again and let us know if you still get the error. 
Kind regards,
Mehri
